#!/bin/bash
mkdir -p /etc/initramfs-tools/hooks
mkdir -p /etc/initramfs/post-update.d
mkdir -p /etc/bash_completion.d

share=/usr/share/velvettools

cp ${share}/hooks/during /etc/initramfs-tools/hooks/velvet-build
cp ${share}/hooks/after /etc/initramfs/post-update.d/velvet-build
cp ${share}/bash/velvettools /etc/bash_completion.d/velvettools

if [ "$1" = "configure" ]; then
    systemctl enable vtcheck.service
fi

if [ ! -f "/etc/velvettools/config" ]; then
    mkdir -p /etc/velvettools
    cp /usr/share/velvettools/config /etc/velvettools/config
fi

dpkg-trigger --await bash-completion