#!/bin/bash
VERSION=0.6.8
RELEASENUMBER=1 #only increse temporary if fix touches only deb/DEBIAN

rm -rf deb

mkdir deb

#deb structure
mkdir -p deb/usr/local/bin
mkdir -p deb/DEBIAN
mkdir -p deb/etc/bash_completion.d
mkdir -p deb/etc/velvettools
mkdir -p deb/lib/systemd/system
mkdir -p deb/usr/share/velvettools/help
mkdir -p deb/usr/share/velvettools/hooks
mkdir -p deb/usr/share/velvettools/bash
mkdir -p deb/etc/initramfs-tools/hooks
mkdir -p deb/etc/initramfs/post-update.d

#basic deb package info
cp other/control deb/DEBIAN/control -v
cp other/postinst deb/DEBIAN/postinst -v
cp other/postrm deb/DEBIAN/postrm -v
cp other/prerm deb/DEBIAN/prerm -v
sed -i "s/VERSION/${VERSION}/g" deb/DEBIAN/control

#main binaries (bash scripts)
cp scripts/vt* deb/usr/local/bin/ -v

#bash autocompletion
cp bashcompletion/velvettools deb/usr/share/velvettools/bash/velvettools -v

#help pages
cp helppages/* deb/usr/share/velvettools/help/ -v

#initramfs hooks
cp initramfs-hooks/during deb/usr/share/velvettools/hooks/during -v
cp initramfs-hooks/after deb/usr/share/velvettools/hooks/after -v

#daemon
cp daemon/vtcheck.service deb/lib/systemd/system/vtcheck.service

#default config
cp other/config deb/usr/share/velvettools/config -v

dpkg-deb --build deb

#<package-name>_<version>-<release-number>_<architecture>
mv deb.deb velvettools-${VERSION}-${RELEASENUMBER}_all.deb -v