#!/bin/bash
# For whatever reason, after an initramfs update, I can't access that info, or I'm reading env output wrong >:3
source /etc/velvettools/config
if [ "$init_gen_hook" != "y" ];then
    exit 0
fi

echo -n "$version" > /boot/to-update
