#!/bin/bash

source $(dirname $BASH_SOURCE)/vtcommon
source $(dirname $BASH_SOURCE)/vtcommon-flash

#imported from vtcommon
need_root

get_kver ${1}

check_flashable_kver

id=2
load_config
part=$main_part

echo flashing test partition
flash_procedure "$1" "$2"

cgpt add -i ${id} -S 0 -T 1 -P 15 /dev/${pdisk}